New diag buttons
impermeable/waterproof-vscode pull request #127
Opened 2024-12-10 10:46 UTC by raulTUe

### Description
Diagnostic Buttons Replace and Insert have been added, to allow for users to use diagnostics for their proof at the click of a button. Now focus on a codeblock is no longer needed, and correct indentation has been applied. 
### Changes
A new updateDiagnostics method has been added, which ensures that the buttons are updated based on all the diagnostics in the line. If there is an error, then a replace button appears for all diagnostics, and if there is no error then the insert button appears for all diagnostics. Moreover, the copy button now has some responsiveness, and tells the user when the text has been copied to their clipboard.
### Testing this PR
You can test it by trying different syntax errors or by inputting relevant tactics in the editor (as seen in the tutorial section 17). You can also place your cursor on a different codeblock and click the diag buttons to test the focus.

2024-12-19 08:30 UTC, jim-portegies commented on editor/src/kroqed-editor/codeview/nodeview.ts
> +		for (const diag of diagCopy) {
It looks like something is happened here for every diagnostics, and in cases there are many errors in the code, I would expect this to become very slow. Since it seems this function is called when a particular diagnostic is added, I am wondering if one can work with that diagnostic as it is coming in (without needing to loop through all diagnostics).

2025-01-13 14:00 UTC, jim-portegies requested changes
The feedback on copying is now much better, but maybe we should stay closer to the color scheme that we are using. Can we make use of one of the theme colors?

Beyond that, the indentation still doesn't work properly. If I write down
```
  Expand the definition of supremum.
```
and click "Replace", then it gets four leading spaces instead of two. If it has four leading spaces to begin with, it receives eight leading spaces after replacing.

2025-01-13 14:00 UTC, jim-portegies commented
In addition, I think we should not change the `vscode/settings.json` file

2025-01-22 07:05 UTC, pimotte requested changes
Two small nitpicks, tested and behaviour looks good.

2025-01-22 07:05 UTC, pimotte commented on editor/src/kroqed-editor/codeview/nodeview.ts
> +		// Create the notification element
Could you extract this styling to a css file in kroqed-editor/styles/ (either an appropriate existing one, or a new one if you don't think it fits anywhere?)

If you use a css class, then you can add that like [here with empty code cells](https://github.com/impermeable/waterproof-vscode/blob/42fbf0b9bf7c2190b69895d3232bc5b5982127fd/editor/src/kroqed-editor/codeview/nodeview.ts#L69) and then the styling is nicely seperated from the behaviour:)

2025-01-22 07:05 UTC, pimotte commented on .vscode/settings.json
> +    }
```suggestion
    "js/ts.implicitProjectConfig.target": "ESNext"
```

2025-01-31 14:47 UTC, DikieDick approved these changes
Approved by me. I wanted to comment that the styling could be centralized to the `styles.css` file imported in `editor.ts` but @pimotte has already fixed this.

2025-01-31 14:56 UTC, merged