Added coq-syntax option to change tactics which show up for autocompletion
impermeable/waterproof-vscode pull request #40
Opened 2023-11-02 16:14 UTC by driverag22

Added new tacticsCoq.json file with the normal coq-syntax tactics.

Also added a setting to change coq-syntax. The information for the selected syntax is passed to editor.ts, which initializes the tactics.ts singleton accordingly.

Laslty, implemented singleton method in tactics.ts to use normal or coqTactics based on how the singleton is initialized by editor.ts Editor.ts "knows" what to initialize the singleton to based on the setting selected by the user. Moreover, the singleton can be "overriden" (i.e., can be initialized more than once) such that if the setting changes, the singleton will change accordingly.

coqTacticsData.json was also created and tactics were added, but with no description and very basic examples. Showing the coq tactics under the tactics menu is not yet implemented.

2023-11-03 09:14 UTC, jim-portegies commented
@driverag22 If I open the tactics panel, I still see the Waterproof tactics. Was this intended?

2023-11-03 09:32 UTC, driverag22 commented
> @driverag22 If I open the tactics panel, I still see the Waterproof tactics. Was this intended?

Yeah, since we weren't sure how we wanted it I left it like this for now. We can freeze the PR for now and I can implemented that sometime at the start of Q2 if needed.

2023-11-06 14:08 UTC, jim-portegies requested changes

2023-11-06 14:08 UTC, jim-portegies commented on package.json
> +        "title": "Coq Syntax",
```suggestion
        "title": "Standard Coq Syntax",
```

2023-11-06 14:08 UTC, jim-portegies commented on package.json
> +            "description": "Enable coq syntax; if true, coq syntax will be used instead of coq-waterproof syntax."
```suggestion
            "description": "Enable Standard Coq syntax; if true, standard Coq syntax will be used instead of the Waterproof proof language."
```

2023-11-06 14:11 UTC, jim-portegies approved these changes

2023-11-06 14:16 UTC, merged