Show notices as diagnostics by default
impermeable/waterproof-vscode pull request #88
Opened 2024-10-05 11:08 UTC by jim-portegies

Best effect with the changes currently in [this PR](https://github.com/impermeable/coq-waterproof/pull/84)

2024-10-05 11:58 UTC, DikieDick requested changes

2024-10-05 11:58 UTC, DikieDick commented on src/lsp-client/clientTypes.ts
> +    show_waterproof_info_messages: boolean;
```suggestion
    show_coq_info_messages: boolean;
```

We can't rename these as they are passed to the `coq-lsp` instance and parsed there. So internally we have to keep the 'coq' name, while for the external/user facing side 'waterproof' is fine.

2024-10-05 11:58 UTC, DikieDick commented on src/lsp-client/clientTypes.ts
> +            show_waterproof_info_messages: wsConfig.show_waterproof_info_messages,
```suggestion
            show_coq_info_messages: wsConfig.show_waterproof_info_messages,
```

See comment above.

2024-10-05 12:58 UTC, jim-portegies commented on src/lsp-client/clientTypes.ts
> +            show_waterproof_info_messages: wsConfig.show_waterproof_info_messages,
Thanks! Apparently I didn't know how this worked.

2024-10-07 16:31 UTC, DikieDick reviewed
Looks good to me.

2024-10-07 16:32 UTC, DikieDick approved these changes

2024-10-10 19:32 UTC, merged